### ISSUE TITLE
Create pinax-invitations documentation from old Kaleo docs

### ISSUE THREAD

**Issue by jacobwegner** [pinax/pinax-invitations#15]

**Comment by jacobwegner** [comment]
Documentation for pinax apps is moving to [pinaxproject.com/pinax](http://pinaxproject.com/pinax)

**Comment by jacobwegner** [comment]
Previous documentation available at http://kaleo.readthedocs.org/en/latest/index.html.

**Comment by ossanna16** [comment]
@jacobwegner Do you think this would be a good "first-timers-only" issue for someone looking to make their first open source contribution?

**Comment by grahamu** [comment]
Done in https://github.com/pinax/pinax-invitations/pull/31.
