### ISSUE TITLE
Document migrations in 2.1.x release

### ISSUE THREAD

**Issue by jacobwegner** [pinax/pinax-invitations#16]
Roughly:
- Renaming the tables prefixes from `kaleo` to `invitations`
- How to fake initial migrations for the app when upgrading

**Comment by john2x** [comment]
Hi. I'm trying to upgrade from kaleo to the latest version. How do I run the migration?

**Comment by ossanna16** [comment]
@john2x Would you mind joining our Pinax project Slack channel (http://slack.pinaxproject.com) and asking your question there? We have a designated #pinax-invitations channel. In case of questions you will usually get help faster if you ping us in Slack 😊

**Comment by KatherineMichel** [comment]
Closing issue. Probably not relevant by now.
